plugin.plugin_configuration.payment_method_configuration.omnipay_paypal_standard:
  type: plugin.plugin_configuration.payment_method_configuration.payment_basic

plugin.plugin_configuration.payment_method_configuration.omnipay_paypal_express:
  type: plugin.plugin_configuration.payment_method_configuration.payment_basic

plugin.plugin_configuration.payment_method_configuration.omnipay_sagepay_direct:
  type: plugin.plugin_configuration.payment_method_configuration.payment_basic

plugin.plugin_configuration.payment_method_configuration.omnipay_sagepay_server:
  type: plugin.plugin_configuration.payment_method_configuration.payment_basic
